# Generated by Django 3.2.8 on 2021-10-22 12:14

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=30)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Dept', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_No', models.CharField(default=None, max_length=20)),
                ('Reg_No', models.CharField(default=None, max_length=20)),
                ('Name', models.CharField(default=None, max_length=30)),
                ('DOB', models.DateField(default=None)),
                ('Phone', models.CharField(default=None, max_length=10)),
                ('Dept', models.CharField(default=None, max_length=20)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Father_Name', models.CharField(default=None, max_length=20)),
                ('Address', models.CharField(default=None, max_length=100)),
                ('Nationality', models.CharField(default=None, max_length=15)),
                ('Religion', models.CharField(default=None, max_length=10)),
                ('Caste_Community', models.CharField(default=None, max_length=5)),
                ('Scholarship', models.BooleanField(default=False)),
                ('Date_Of_Admission', models.DateField(default=None)),
                ('Date_Of_Leaving', models.DateField(default=None)),
                ('Purpose_Of_TC', models.CharField(default=None, max_length=50)),
                ('No_Dues_Certificate', models.BooleanField(default=False)),
                ('Conduct', models.CharField(default=None, max_length=10)),
                ('Signature_Of_HOD', models.BooleanField(default=False)),
                ('Due_Department', models.BooleanField(default=False)),
                ('Due_Library', models.BooleanField(default=False)),
                ('Due_PE', models.BooleanField(default=False)),
                ('Due_NSS', models.BooleanField(default=False)),
                ('Due_Hostel', models.BooleanField(default=False)),
                ('Due_Office', models.BooleanField(default=False)),
                ('Due_Labs', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is staff')),
                ('is_student', models.BooleanField(default=False, verbose_name='Is student')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
