# Generated by Django 3.2.8 on 2021-10-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Dept', models.CharField(max_length=20)),
            ],
        ),
    ]
