# Generated by Django 3.2.8 on 2021-11-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_staff_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Year',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
