# Generated by Django 3.2.8 on 2021-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211022_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_No', models.CharField(default=None, max_length=20, null=True)),
                ('Dept', models.CharField(default=None, max_length=20, null=True)),
                ('Verefication', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
