# Generated by Django 3.2.8 on 2021-10-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='Verefication',
            new_name='Verification',
        ),
    ]
