# Generated by Django 3.2.8 on 2021-11-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_staff_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_No', models.CharField(default=None, max_length=20, null=True)),
                ('Reg_No', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('DOB', models.DateField(blank=True, default=None, null=True)),
                ('Phone', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Dept', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('Father_Name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Nationality', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('Religion', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Caste_Community', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('Date_Of_Admission', models.DateField(blank=True, default=None, null=True)),
                ('Date_Of_Leaving', models.DateField(blank=True, default=None, null=True)),
                ('Purpose_Of_TC', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Conduct', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Applied', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
