# Generated by Django 3.2.8 on 2021-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211024_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='Class',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
