# Generated by Django 3.2.8 on 2021-11-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_No', models.CharField(default=None, max_length=20, null=True)),
                ('Due', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Due_Date', models.DateField(blank=True, default=None, null=True)),
                ('is_Done', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reg_No', models.CharField(default=None, max_length=20, null=True)),
                ('Dept', models.BooleanField(blank=True, default=False, null=True)),
                ('Library', models.BooleanField(blank=True, default=False, null=True)),
                ('Hostel', models.BooleanField(blank=True, default=False, null=True)),
                ('Office', models.BooleanField(blank=True, default=False, null=True)),
                ('Labs', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Year',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
