# Generated by Django 3.2.8 on 2021-11-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211122_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='First',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
