# Generated by Django 3.2.8 on 2021-10-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211025_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Scholarship',
        ),
    ]
