# Generated by Django 3.2.8 on 2021-11-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_student_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='due',
            name='Due_Date',
        ),
        migrations.AddField(
            model_name='due',
            name='Dept',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
