# Generated by Django 3.2.8 on 2021-11-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211122_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='Hostel',
            new_name='Due',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='Labs',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='Library',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='Office',
        ),
        migrations.AddField(
            model_name='requests',
            name='Year',
            field=models.IntegerField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Dept',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
