# Generated by Django 3.2.8 on 2021-11-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211105_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Applied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
