# Generated by Django 3.2.8 on 2021-11-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211123_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='Labs',
            new_name='PG_Lab',
        ),
        migrations.AddField(
            model_name='requests',
            name='UG_Lab',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
