# Generated by Django 3.2.8 on 2021-11-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_student_applied'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dept',
        ),
    ]
