# Generated by Django 3.2.8 on 2021-11-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211124_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Level',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
